### ISSUE TITLE
🚀 iOS 14 DNS-Profile (.mobileconfig)

### ISSUE THREAD

**Issue by privacy-advo** [ookangzheng/blahdns#153]
**Is your feature request related to a problem?**
Traffic leakage due to no always-on-VPN option, IKEv2 needed, while using it with DNSCloak [@s-s]

**Describe the solution you'd like**
iOS 14 DNS-Profile

**Describe alternatives you've considered**
An IKEv2 based Always-On-VPN profile.

**Comment by ookangzheng** [comment]
I haven't try it out with .mobileconfig though, I'm using AdBlock app on iOS with BlahDNS as up stream server. It doesn't leak my DNS traffic.

**Comment by privacy-advo** [comment]
Thank you for the fast response.
Are you referring to "AdBlock" by FutureMind? There are a lot of different "AdBlock + x" named apps.

**Comment by ookangzheng** [comment]
Sorry, I mean Adguard

**Comment by privacy-advo** [comment]
Sadly, the VPN AdGuard is providing is only "on-demand". This VPN will leak data each time the device switches between sleep/active. This VPN needs to be established (on-demand). There are already queries prior it is established. I just rechecked it with iPhone iOS 14.3 and newest AdGuard V. 4.0.4 (588). 

Just checked the AdGuard repo. There's even an open issue by @ameshkov:
https://github.com/AdguardTeam/AdguardForiOS/issues/1692

**Comment by ookangzheng** [comment]
Interesting, Maybe I can generate a fake ikev2 profile for you?
But how can you redirect local DNS query to other DNSCloak? 

Do DNSCloak support proxy mode?

**Comment by privacy-advo** [comment]
Unfortunately, I can't answer your question. Maybe the developer of DNSCloak @s-s could answer this question.


////

The solution I suggested would be a separate iOS 14 DNS profile. This feature was introduced with iOS 14. There are related projects on Github:
https://github.com/paulmillr/encrypted-dns

dnsforge.de for example provides a similar, even signed, .mobileconfig. See under "Clients" / "iOS
Ab iOS 14: dnsforge-doh.mobileconfig"
https://dnsforge.de/

Nevertheless, this would not enable a user to use custom blocklists as used in DNSCloak.

**Comment by privacy-advo** [comment]
Unfortunately, I can't answer your question. Maybe the developer of DNSCloak @s-s could answer this question.

**Comment by Mikaela** [comment]
https://encrypted-dns.party/ has mobileconfigs for BlahDNS too in case it can help. Just remember to open it in Safari

**Comment by privacy-advo** [comment]
Thank you. Did you check if there's the same kind of leakage as with the on-demand VPNs (AdGuard/DNSCloak etc.).

**Comment by nitrohorse** [comment]
> Did you check if there's the same kind of leakage as with the on-demand VPNs (AdGuard/DNSCloak etc.).

I've previously done some testing with NextDNS profiles and observed this kind of leakage (that [Proton also describes](https://protonvpn.com/blog/apple-ios-vulnerability-disclosure/)) _does appear to occur_ even with mobileconfig profiles unfortunately (but someone would need to confirm this).

Related, I've observed a different kind of leakage, one where Apple service specific requests (for example Push notifications (`*-courier.push.apple.com`)) bypass the on-demand VPN profiles for resolution. I don't have a source for this but think this is actually expected behavior. Mobileconfigs _don't_ appear to suffer from this type of leakage and do resolve Apple service requests.

So tl;dr I think mobileconfigs have "less" leakage than on-demand VPNs. But the only way to have no leakage is:
- use an [always-on VPN](https://support.apple.com/guide/deployment-reference-ios/always-on-vpn-iore8b083096/1/web/1) (requires device to be supervised)
- or regularly toggle airplane mode on sleep/active/network changes with a mobileconfig encrypted DNS profile set (still not full proof).

**Comment by privacy-advo** [comment]
Just quickly checked the behaviour of blahdns .mobileconfigs [@Mikaela] and I observed no leakage on an wifi-only iPad during on/off. Didn't test the switch between mobile data / wifi on an iPhone so far. But that looks promising.

Further, Adguard promised a fix for the leakage problem with on-demand VPN:
https://github.com/AdguardTeam/AdguardForiOS/issues/1692#issuecomment-755170807

**Comment by privacy-advo** [comment]
Update:
Sadly, Adguard concluded after further investigation that there's no fix for the leakage while using the "normal" VPN functionality.
https://github.com/AdguardTeam/AdguardForiOS/issues/1692#issuecomment-772512794

Damn. 👎
