### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by obeho** [ookangzheng/blahdns#238]
Hello @ookangzheng 

I know you're probably busy, but I just saw the urgent call for donations. I'm sure many users of this project's services are wondering the reason behind such a sudden spike in the server fees.

I would also like to explore the possibility of expanding payment methods for donations (other than via PayPal), privately, shoud I email you at: k*********o@co****tx.com?

**Comment by ookangzheng** [comment]
_Disclaimer: I'm not intent to make money for this project. As the project growing and have more connections, I'd like to try something new and learn from doing to improve BlahDNS project. Though, without donation, I'm still willing to pay server fees with my savings._ 

Actually the amount I wrote is estimate amount (350 USD) will be use for entire 2022 year. 

**Here are my draft plan**

1. Due to recent high amount of traffic, I plan upgrade to more CPUs plan ( around 30 ~ 35 USD /m )
2. Upgrade StatusPage to paid plan. (9.95 USD)
3. Setup GeoDNS routing for BlahDNS, it is not cheap for those traffic and routing rules (Not yet include in current budget)

If you prefer other than Paypal, I have TransferWise and Cryptocurrencies (XMR, LTC, Solana, or USD stable coin (trc-20)) 

@obeho please email me at: oo-git AT boo DoT cat

**Comment by obeho** [comment]
I don't doubt your intentions. The announcement was "USD 350 for server renting fees during Februray 2022", so it was confusing.

Thank you for the details. I think this plan should be put up as a clickable link in the README.

I've emailed you btw (from ob*******d.net)
