### ISSUE TITLE
Video ads on youtube are no longer blocked

### ISSUE THREAD

**Issue by Dadan59DK** [ookangzheng/blahdns#3]
Hello, I'm the one who contacted you about the problem with Snapchat (the problem came back ^^), now it's youtube that no longer blocks video ads, on my box or on my smart tv, as soon as I watch a video, I get several ads per minute, I noticed that your competitors like adguard don't block them anymore, filter problem? Oh yes, I forgot your dns also blocks facebook widget, twitter, on my website, I don't see anything, is it possible to reactivate widget (http://dunkerquestreetradio.tk)

Screenshot widget facebook: http://www.turbopix.fr/v/ymslshif82

here is a list of sites where ads are not blocked: 

-http://www.emule-island.ru (Screenshot: http://www.turbopix.fr/v/njn9eqhpfa)
-https://ww1.extreme-d0wn.com/home.html (Screenshot: http://www.turbopix.fr/v/pkmgq6kcxn)

Is it possible to add the adblock killer filter? Thank you

https://reek.github.io/anti-adblock-killer/

**Comment by ookangzheng** [comment]
@Dadan59DK Thanks for your question.
1. via DNS based Adblock can't block Youtube ads in the app. because of Google ship those ads via HTTPS. DNS based Adblock only can block HTTP.
2. I filtered www.emule-island.ru, the ads come from the same domain, so I can't block it.
3. Likewise, ww1.extreme-d0wn.com/home.html ( same scenario )
4. Unfortunately, I can't add the anti-adblock-killer, because DNS based only block DOMAIN, not on specific content (HTML tag or classes).
5. facebook widget fixed
